Specify PendingIntent.FLAG_IMMUTABLE to avoid lintVitalRelease error.
* What went wrong:
Execution failed for task ':handheld:lintVitalBugdroidRelease'.
> Lint found fatal errors while assembling a release target.

  Fix the issues identified by lint, or create a baseline to see only new errors.
  To create a baseline, run `gradlew updateLintBaseline` after adding the following to the module's build.gradle file:
  ```
  android {
      lint {
          baseline = file("lint-baseline.xml")
      }
  }
  ```
  For more details, see https://developer.android.com/studio/write/lint#snapshot

  /Users/carmen/dev/projects/perso/nounours-android/handheld/src/main/java/ca/rmen/nounours/android/handheld/AnimationSaveService.java:119: Error: Missing PendingIntent mutability flag [UnspecifiedImmutableFlag]
              PendingIntent pendingShareIntent = PendingIntent.getActivity(this, 0, shareIntent, 0);
                                                                                                 ~
  /Users/carmen/dev/projects/perso/nounours-android/handheld/src/main/java/ca/rmen/nounours/android/handheld/AnimationSaveService.java:150: Error: Missing PendingIntent mutability flag [UnspecifiedImmutableFlag]
          return PendingIntent.getActivity(this, 0, intent, 0);
                                                            ~

     Explanation for issues of type "UnspecifiedImmutableFlag":
     Apps targeting Android 12 and higher must specify either FLAG_IMMUTABLE or
     FLAG_MUTABLE when constructing a PendingIntent.

     FLAG_IMMUTABLE is available since target SDK 23, and is almost always the
     best choice. See
     https://developer.android.com/guide/components/intents-filters#CreateImmuta
     blePendingIntents for a list of common exceptions to this rule.

     https://developer.android.com/about/versions/12/behavior-changes-12#pending-intent-mutability
     https://goo.gle/UnspecifiedImmutableFlag

  2 errors